### ISSUE TITLE
usage with moment.js

### ISSUE THREAD

**Issue by sarbazx** [MananTank/radioactive-state#4]
Hi cool library, I am having problem with momentjs, when state value is moment object or array, state is giving proxy not the moment object or the array. How to get plain object or array not the proxied one?

**Comment by MananTank** [comment]
Hi, Thanks for bringing this to my attention. 

I have added this feature to 1.3.7 now.
you can now get the non-proxied version of `state` using `state.__target__`

( I'm calling it to __target__ because it is returning the target of the proxy, which is the non-proxied version )

Example: https://codesandbox.io/s/counter-example-forked-1jng7?file=/src/Counter.js

**Comment by sarbazx** [comment]
currently there is problem when state contains nested object or big array. It gets it as undefined

**Comment by MananTank** [comment]
Can you add a link to sandbox, so I can check it out
